name: check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check --workspace --all-targets

      - name: Test
        run: cargo test --workspace

      - name: Parser Fixture Tests
        run: cargo test -p sevenmark_parser --features include_locations --test comprehensive_parser_tests

      - name: Clippy
        run: cargo clippy --workspace --all-targets

      - name: Format
        run: cargo fmt --check
